### PR TITLE
Fix empty value decoding in primitive readers

### LINKED ISSUE #19: Primitive readers don't handle empty values correctly
Passing a slice of length 0 to `Read()` works normally but it fails with `EOF` if the buffer is empty so any empty value that occurs at the end of the buffer will result in an `EOF` instead of empty. This is a confirmed issue with `ReadBytes()` but no confirmation on other primitives yet.

### PR DESCRIPTION
**Pull request by joao-r-reis**
Fix #19

### CODE REVIEW

File: primitive/bytes_map_test.go [hunk 1]
```diff
@@ -102,11 +102,18 @@ func TestReadBytesMap(t *testing.T) {
...
-			assert.Equal(t, tt.remaining, buf.Bytes())
 			assert.Equal(t, tt.err, err)
+			remaining := make([]byte, buf.Len())
+			_, err = buf.Read(remaining)
+			if len(tt.remaining) == 0 {
+				assert.NotNil(t, err)
+			} else {
+				assert.Nil(t, err)
+				assert.Equal(t, tt.remaining, remaining)
+			}
```
Comment (adutra) [inline primitive/bytes_map_test.go:116]: I think this and similar spots could be simplified:

```suggestion
			remaining, _ := ioutil.ReadAll(buf)
			assert.Equal(t, tt.remaining, remaining)
```

I think it's not necessary to capture the error from `ReadAll` since we know it cannot be non-nil.

**Review by adutra — CHANGES_REQUESTED** [review]

File: primitive/bytes_map_test.go (hunk 1 above)
Comment (joao-r-reis) [reply primitive/bytes_map_test.go]: 👍  done

**Review by adutra — APPROVED** [review]
